version: "3"
services:
    db:
        image: "postgres:alpine"
        restart: always
        env_file:
            - db.env
        ports:
            - "8056:5432"
        expose:
            - "8056"

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - app.env
        depends_on:
            - db
